<script setup>
import { onMounted, ref } from "vue";

import DataArticle from "./Cards/DataArticle.vue";
import IndexCarouselComponent from "./carousels/IndexCarouselComponent.vue";

const items = ref([]);

onMounted(() => {
  const data = [
    {
      id: 13023,
      title: "2 Pièces - Sanitaire",
      location: " Bidossessi, Abomey-Calavi",
      prix: 51000,
      promoter: "The Catalyzer",
      status: "À louer",
      images: ["image1.jpg", "image2.jpg", "image3.jpg"],
      type: ["2 Pieces"],
    },
    {
      id: 54454,
      title: "3 Pièces - Sanitaire",
      location: " Bidossessi, Abomey-Calavi",
      prix: 91000,
      promoter: "THome Dom",
      status: "À louer",
      images: ["image4.jpg", "image5.jpg", "image6.jpg"],
      type: ["3 Pieces"],
    },
    {
      id: 4606,
      title: "1 Pièce - Sanitaire",
      location: " Bidossessi, Abomey-Calavi",
      prix: 50000,
      promoter: "The Catalyzer",
      status: "À louer",
      images: ["image2.jpg", "image1.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
      type: ["1 Piece"],
    },
    {
      id: 45128,
      title: "2 Pièces - Simple",
      location: " Bidossessi, Abomey-Calavi",
      prix: 40000,
      promoter: "The Catalyzer",
      status: "À louer",
      images: ["image9.jpg", "image10.jpg", "image11.jpg"],
      type: ["2 Pieces", "Simple"],
    },
    {
      id: 58786,
      title: "3 Pièces - Sanitaire",
      location: " Bidossessi, Abomey-Calavi",
      prix: 51000,
      promoter: "ADA Home",
      status: "À louer",
      images: ["image12.jpg", "image13.jpg", "image14.jpg"],
      type: ["3 Pieces", "Sanitaire"],
    },
    {
      id: 40228,
      title: "2 Pièces - Sanitaire",
      location: " Bidossessi, Abomey-Calavi",
      prix: 90000,
      promoter: "The Catalyzer",
      status: "À louer",
      images: ["image14.jpg", "image15.jpg", "image16.jpg"],
      type: ["2 Pieces", "Sanitaire"],
    },
    {
      id: 455648,
      title: "2 Pièces - Simple",
      location: " Bidossessi, Abomey-Calavi",
      prix: 40000,
      promoter: "Azus pro",
      status: "À louer",
      images: ["image20.jpg", "image18.jpg", "image1.jpg"],
      type: ["2 Pieces", "Simple"],
    },
    {
      id: 45060,
      title: "2 Pièces - Sanitaire",
      location: " Bidossessi, Abomey-Calavi",
      prix: 40000,
      promoter: "The Catalyzer",
      status: "À louer",
      images: ["image9.jpg", "image10.jpg", "image11.jpg"],
      type: ["2 Pieces", "Sanitaire"],
    },
    {
      id: 466,
      title: "1 Pièce - Sanitaire",
      location: " Bidossessi, Abomey-Calavi",
      prix: 50000,
      promoter: "The Catalyzer",
      status: "À louer",
      images: ["image2.jpg", "image1.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
      type: ["1 Piece"],
    },
    {
      id: 49948,
      title: "2 Pièces - Simple",
      location: " Bidossessi, Abomey-Calavi",
      prix: 40000,
      promoter: "The Catalyzer",
      status: "À louer",
      images: ["image9.jpg", "image10.jpg", "image11.jpg"],
      type: ["2 Pieces", "Simple"],
    },
    {
      id: 58696,
      title: "3 Pièces - Sanitaire",
      location: " Bidossessi, Abomey-Calavi",
      prix: 51000,
      promoter: "ADA Home",
      status: "À louer",
      images: ["image12.jpg", "image13.jpg", "image14.jpg"],
      type: ["3 Pieces", "Sanitaire"],
    },
    {
      id: 47648,
      title: "2 Pièces - Sanitaire",
      location: " Bidossessi, Abomey-Calavi",
      prix: 90000,
      promoter: "The Catalyzer",
      status: "À louer",
      images: ["image14.jpg", "image15.jpg", "image16.jpg"],
      type: ["2 Pieces", "Sanitaire"],
    },
    {
      id: 422648,
      title: "2 Pièces - Simple",
      location: " Bidossessi, Abomey-Calavi",
      prix: 40000,
      promoter: "Azus pro",
      status: "À louer",
      images: ["image20.jpg", "image18.jpg", "image1.jpg"],
      type: ["2 Pieces", "Simple"],
    },

    {
      id: 4606,
      title: "1 Pièce - Sanitaire",
      location: " Bidossessi, Abomey-Calavi",
      prix: 50000,
      promoter: "The Catalyzer",
      status: "À louer",
      images: ["image2.jpg", "image1.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
      type: ["1 Piece"],
    },
    {
      id: 45648,
      title: "2 Pièces - Simple",
      location: " Bidossessi, Abomey-Calavi",
      prix: 40000,
      promoter: "The Catalyzer",
      status: "À louer",
      images: ["image9.jpg", "image10.jpg", "image11.jpg"],
      type: ["2 Pieces", "Simple"],
    },
    {
      id: 58696,
      title: "3 Pièces - Sanitaire",
      location: " Bidossessi, Abomey-Calavi",
      prix: 51000,
      promoter: "ADA Home",
      status: "À louer",
      images: ["image12.jpg", "image13.jpg", "image14.jpg"],
      type: ["3 Pieces", "Sanitaire"],
    },
    {
      id: 40648,
      title: "2 Pièces - Sanitaire",
      location: " Bidossessi, Abomey-Calavi",
      prix: 90000,
      promoter: "The Catalyzer",
      status: "À louer",
      images: ["image14.jpg", "image15.jpg", "image16.jpg"],
      type: ["2 Pieces", "Sanitaire"],
    },
    {
      id: 455648,
      title: "2 Pièces - Simple",
      location: " Bidossessi, Abomey-Calavi",
      prix: 40000,
      promoter: "Azus pro",
      status: "À louer",
      images: ["image20.jpg", "image18.jpg", "image1.jpg"],
      type: ["2 Pieces", "Simple"],
    },
    {
      id: 148,
      title: "5 Pièces - Simple",
      location: " Bidossessi, Abomey-Calavi",
      prix: 120000,
      promoter: "Azus pro",
      status: "À louer",
      images: ["image20.jpg", "image18.jpg", "image1.jpg"],
      type: ["5 Pieces", "Simple"],
    },
    {
      id: 13,
      title: "2 Pièces - Simple",
      location: " Bidossessi, Abomey-Calavi",
      prix: 35000,
      promoter: "Azus pro",
      status: "À louer",
      images: ["image20.jpg", "image18.jpg", "image1.jpg"],
      type: ["2 Pieces", "Simple"],
    },
    {
      id: 148,
      title: "2 Pièces - Simple",
      location: " Bidossessi, Abomey-Calavi",
      prix: 40000,
      promoter: "The houser pro",
      status: "À louer",
      images: ["image20.jpg", "image18.jpg", "image1.jpg"],
      type: ["2 Pieces", "Simple"],
    },
    {
      id: 45,
      title: "2 Pièces - Carrelée",
      location: " Bidossessi, Abomey-Calavi",
      prix: 150000,
      promoter: "Azus pro",
      status: "À louer",
      images: ["image20.jpg", "image18.jpg", "image1.jpg"],
      type: ["2 Pieces", "carrelee"],
    },
    {
      id: 4,
      title: "Guest House - Carrelée",
      location: " Bidossessi, Abomey-Calavi",
      prix: 300000,
      promoter: "Azus pro",
      status: "À louer",
      images: ["image20.jpg", "image18.jpg", "image1.jpg"],
      type: ["2 Pieces", "Carrelee"],
    },
    {
      id: 422,
      title: "2 Pièces - Simple",
      location: " Bidossessi, Abomey-Calavi",
      prix: 40000,
      promoter: "Azus pro",
      status: "À louer",
      images: ["image20.jpg", "image18.jpg", "image1.jpg"],
      type: ["2 Pieces", "Simple"],
    },
  ];
  items.value = data;
});
</script>
<template>
  <IndexCarouselComponent />
  <!-- home filter-->
  <!--Articles-->

  <DataArticle :items="items" />
</template>
