const icones = ["login"="login.svg",
        "logout"="logout.svg",
        "user"="user.svg",
        "home"="home.svg",
        "settings"="settings.svg",
        "cart"="cart.svg",
        "help"="help.svg",
        "search"="search.svg",
        "info"="info.svg",
        "success"="success.svg",
        "error"="error.svg",
        "warning"="warning.svg",
        "infoCircle"="info-circle.svg",
        "exclamationTriangle"="exclamation-triangle.svg",
        "exclamationCircle"="exclamation-circle.svg",
        "questionCircle"="question-circle",
        "plus"="plus.svg",
        "minus"="minus.svg",
        "times"="times.svg",
        "check"="check.svg",
        "ban"="ban.svg",
        "trash"="trash.svg",
        "copy"="copy.svg",
        "paste"="paste.svg",
        "userPlus"="user-plus.svg",
        "userMinus"="user-minus.svg",
        "userCheck"="user-check.svg",
        "userTimes"="user-times.svg",
        "sortUp"="sort-up.svg",
        "sortDown"="sort-down.svg",
        "sortAmountUp"="sort-amount-up.svg",
        "sortAmountDown"="sort-amount-down.svg",
        "filter"="filter.svg",
        "plusCircle"="plus-circle.svg",
        "minusCircle"="minus-circle.svg",
        "plusSquare"="plus-square.svg",
        "loginRounded"="login-rounded.svg",
        "logoutRounded"="logout-rounded.svg",
        "userRounded"="user-rounded.svg",
        "userCog"="user-cog.svg",
        "userEdit"="user-edit.svg",
        "homeRounded"="home-rounded.svg",
        "settingsRounded"="settings-rounded.svg",
        "cartRounded"="cart-rounded.svg",
        "helpRounded"="help-rounded.svg",
        "searchRounded"="search-rounded.svg",
        "infoRounded"="info-rounded.svg",
        "successRounded"="success-rounded.svg",
        "errorRounded"="error-rounded.svg",
        "warningRounded"="warning-rounded.svg",
        "infoCircleRounded"="info-circle-rounded.svg",
        "exclamationTriangleRounded"="exclamation-triangle-rounded.svg",
]
        
    


export default icones;